trigger:
  tags:
    include: ['*']
  branches:
    include: ["main"]

pr:
  branches:
    include: ['*']
  paths:
    include:
      - ".azure/docker-build.yml"
      - "dockers/**"
      - "requirements.txt"
      - "requirements/*.txt"
      - "setup.py"
    exclude:
      - "*.md"
      - "**/*.md"


jobs:
  - job: build_push
    strategy:
      matrix:
        'cuda 11.8':
          CUDA_VERSION: '11.8.0'
        'cuda 12.1':
          CUDA_VERSION: '12.1.1'
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "35"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"
    variables:
      PYTHON_VERSION: '3.10'
      imageRepository: 'pytorchlightning/lightning-thunder'
      dockerfilePath: 'dockers/base-cuda/Dockerfile'
      imageTag: 'base-cuda$(CUDA_VERSION)-py$(PYTHON_VERSION)'
    pool: 'lit-rtx-3090'
    workspace:
      clean: all
    steps:
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: 17.09.0-ce
          releaseType: stable

      - bash: |
          set -e
          docker image build \
            -t $(imageRepository):$(imageTag) \
            -f $(dockerfilePath) \
            --build-arg CUDA_VERSION=$(CUDA_VERSION) \
            --build-arg PYTHON_VERSION=$(PYTHON_VERSION) \
            .
          docker image ls
        displayName: 'Build base image'

      - bash: |
          set -e
          echo $(DOCKERHUB_PAT) | docker login --username $(DOCKERHUB_USER) --password-stdin
          docker push $(imageRepository):$(imageTag)
        condition: ne(variables['Build.Reason'], 'PullRequest')
        displayName: 'Push base image'

      #- task: Docker@1
      #  inputs:
      #    containerregistrytype: 'Container Registry'
      #    dockerRegistryEndpoint: 'Docker Hub'
      #    command: 'Build an image'
      #    dockerFile: '$(dockerfilePath)'
      #    imageName: '$(ImageName)'
      #    useDefaultContext: false
      #    buildContext: 'CustomerApi'
      #  displayName: 'Build the Docker image'
      #- task: Docker@1
      #  inputs:
      #    containerregistrytype: 'Container Registry'
      #    dockerRegistryEndpoint: 'Docker Hub'
      #    command: 'Push an image'
      #    imageName: '$(ImageName)'
      #  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      #  displayName: 'Push the Docker image to Dockerhub'
