name: General checks

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  #check-code:
  #  uses: Lightning-AI/utilities/.github/workflows/check-code.yml@main
  #  with:
  #    actions-ref: main

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      azure-dir: ".azure"

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@main
    with:
      actions-ref: main
      import-name: "thunder"
      artifact-name: dist-packages-${{ github.sha }}
      install-flags: "-f https://download.pytorch.org/whl/test/cpu/torch_test.html"
      testing-matrix: |
        {
          "os": ["ubuntu-latest", "windows-latest"],
          "python-version": ["3.10"]
        }

  # todo
  #check-docs:
  #  uses: Lightning-AI/utilities/.github/workflows/check-docs.yml@main
  #  with:
  #    python-version: "3.10"
  #    requirements-file: "requirements/docs.txt"
