name: Code linting

on: [push]

jobs:

  precommit-run:
    uses: Lightning-AI/utilities/.github/workflows/check-precommit.yml@main
    with:
      python-version: "3.10"
      push-fixes: true
    secrets:
      github-token: ${{ secrets.PAT_GHOST }}
