name: Docker build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".github/workflows/ci-dockers-build.yml"
      - "dockers/**"
      - "requirements.txt"
      - "requirements/*.txt"
      - "setup.py"
      - "!*.md"
      - "!**/*.md"
  schedule:
    - cron: "0 0 * * *"  # at the end of every day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

env:
  PUSH_TO_HUB: ${{ github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

jobs:

  build-cuda:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python_version: "3.10", cuda_version: "11.8.0"}
          - {python_version: "3.10", cuda_version: "12.1.1"}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        if: env.PUSH_TO_HUB == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            CUDA_VERSION=${{ matrix.cuda_version }}
          file: dockers/base-cuda/Dockerfile
          push: ${{ env.PUSH_TO_HUB }}
          tags: pytorchlightning/lightning-thunder:base-cuda-py${{ matrix.python_version }}-cuda${{ matrix.cuda_version }}
        timeout-minutes: 55
