name: "Deploy Docs"
on:
  push:
    branches: [main]

jobs:
  # https://github.com/marketplace/actions/deploy-to-github-pages
  build-docs-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-

      - name: Install package & dependencies
        env:
          TORCH_URL: "https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html"
        run: |
          pip --version
          pip install . -U -r requirements.txt -r requirements/docs.txt --find-links ${TORCH_URL}
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get update --fix-missing
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          pip list
        shell: bash

      - name: Make Documentation
        working-directory: ./docs
        run: make html --jobs 2

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
          single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history
        if: success()
